# -*- mode: ruby -*-
# vi: set ft=ruby :
# Set these environment variables before running `vagrant up`:
#   Optional:
#     DEB_CACHE_HOST = Debian package cache, e.g. "http://192.168.96.100:8000" (default: no cache)

# Adjustable settings
CFG_MEMSIZE = ENV['DSE_MEMSIZE']
NETWORK = "192.168.99.199"
HOSTNAME = "cassandra"

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
  config.vm.hostname = HOSTNAME
  config.vm.network :private_network, ip: NETWORK
  config.vm.provision :shell, :inline => "sudo rm /etc/localtime && sudo ln -s /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime", run: "always"
  config.vm.provision "shell", path: "./install_script.sh", env: {DSE_LOGIN:ENV['DSE_LOGIN'], DSE_PASS:ENV['DSE_PASS']}
  config.vm.provider :virtualbox do |v|
    v.name = HOSTNAME
    v.customize ["modifyvm", :id, "--memory", CFG_MEMSIZE]
  end
end
